# Generated by Django 5.1.7 on 2025-03-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bubble',
            name='rank',
            field=models.CharField(choices=[('INICIANTE_VERDE', 'Iniciante Verde'), ('GUARDIAO_DO_ECO', 'Guardião do Eco'), ('DEFENSOR_DA_NATUREZA', 'Defensor da Natureza'), ('HEROI_SUSTENTAVEL', 'Herói Sustentável'), ('LIDER_VERDE', 'Líder Verde')], default='INICIANTE_VERDE', max_length=50),
        ),
    ]
