# Generated by Django 5.1.7 on 2025-03-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolha', '0002_bubble_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bubble',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
