# Generated by Django 5.1.7 on 2025-05-24 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_campanha_campanhaparticipant_gincana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community'),
        ),
        migrations.AlterField(
            model_name='gincana',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community'),
        ),
    ]
