# Generated by Django 5.1.7 on 2025-05-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_campanha_community_alter_gincana_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gincanacompetitor',
            name='points',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
