# Generated by Django 5.1.7 on 2025-05-26 23:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_gincanacompetitor_points'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='campanha',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='gincana',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='quiz',
        ),
        migrations.AlterUniqueTogether(
            name='quizanswer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='quizanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quizanswer',
            name='selected_option',
        ),
        migrations.RemoveField(
            model_name='quizanswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quizoption',
            name='question',
        ),
        migrations.AddField(
            model_name='campanha',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='campaign_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='gincanacompetitor',
            unique_together={('gincana', 'name')},
        ),
        migrations.DeleteModel(
            name='CampanhaParticipant',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizAnswer',
        ),
        migrations.DeleteModel(
            name='QuizOption',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
    ]
