# Generated by Django 5.1.7 on 2025-05-30 19:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_remove_quiz_campanha_remove_quiz_gincana_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campanha',
            new_name='Campaign',
        ),
        migrations.RenameModel(
            old_name='Gincana',
            new_name='Challenge',
        ),
        migrations.RenameModel(
            old_name='GincanaCompetitor',
            new_name='ChallengeCompetitor',
        ),
        migrations.RenameModel(
            old_name='GincanaRecord',
            new_name='ChallengeRecord',
        ),
        migrations.AlterModelOptions(
            name='challengerecord',
            options={'ordering': ['-collected_at'], 'verbose_name': 'Challenge Record', 'verbose_name_plural': 'Challenge Records'},
        ),
    ]
