# Generated by Django 5.1.7 on 2025-06-01 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_rename_campanha_campaign_rename_gincana_challenge_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challengecompetitor',
            old_name='gincana',
            new_name='challenge',
        ),
        migrations.RemoveField(
            model_name='challengerecord',
            name='gincana',
        ),
        migrations.AlterUniqueTogether(
            name='challengecompetitor',
            unique_together={('challenge', 'name')},
        ),
    ]
