# Generated by Django 5.1.7 on 2025-03-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_users_email_alter_users_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
    ]
