# Generated by Django 5.1.7 on 2025-03-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='bio',
            field=models.TextField(default=None, max_length=256, null=True),
        ),
    ]
