# Generated by Django 5.1.7 on 2025-04-08 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_interests_users_location_users_interests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='location',
        ),
    ]
