# Generated by Django 5.1.7 on 2025-03-16 19:11

from django.db import migrations

def create_ranks(apps, schema_editor):
    # Buscando o modelo Difficulty
    Difficulty = apps.get_model('bubble', 'Difficulty')  # Substitua 'app_name' pelo nome do seu app
    Rank = apps.get_model('bubble', 'Rank')  # Substitua 'app_name' pelo nome do seu app

    # Verificando se as dificuldades já existem
    easy = Difficulty.objects.get_or_create(name='Easy', points_for_activity=50)[0]
    medium = Difficulty.objects.get_or_create(name='Medium', points_for_activity=30)[0]
    hard = Difficulty.objects.get_or_create(name='Hard', points_for_activity=10)[0]

    # Ranks a serem criados com a ordem crescente (3 iniciante, 3 intermediário, 3 avançado)
    ranks = [
        # Nível Iniciante
        ('Iniciante Verde', easy, 100),
        ('Guardião do Eco', easy, 150),
        ('Protetor do Planeta', easy, 200),

        # Nível Intermediário
        ('Defensor da Natureza', medium, 300),
        ('Herói Sustentável', medium, 400),
        ('Sustentável Líder', medium, 500),

        # Nível Avançado
        ('Líder Verde', hard, 700),
        ('Guardião da Floresta', hard, 800),
        ('Protetor Global', hard, 1000),
    ]

    # Criando os ranks com os níveis
    for rank_name, difficulty, points in ranks:
        Rank.objects.get_or_create(name=rank_name, difficulty=difficulty, points=points)

class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_ranks),
    ]
