# Generated by Django 5.1.7 on 2025-03-16 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0002_auto_create_ranks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bubble',
            name='rank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='bubble.rank'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='difficulty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='bubble.difficulty'),
        ),
    ]
