# Generated by Django 5.1.7 on 2025-03-16 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0003_alter_bubble_rank_alter_rank_difficulty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='date_time',
            new_name='created_at',
        ),
    ]
