# Generated by Django 5.1.7 on 2025-03-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0004_rename_date_time_checkin_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='xp_earned',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
