# Generated by Django 5.1.7 on 2025-03-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0005_checkin_xp_earned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='xp_earned',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
