# Generated by Django 5.1.7 on 2025-03-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_alter_lesson_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='categories',
            field=models.ManyToManyField(blank=True, to='study.category'),
        ),
    ]
