# Generated by Django 5.1.7 on 2025-04-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_rename_lessoncompletion_lessonlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('checkin', 'Check-in'), ('lesson', 'Lição')], max_length=50),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='condition',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
