from typing import Protocol

from apps.bubble.domain.entities.rank import RankEntity


class RankRepository(Protocol):
    def save(self, entity: RankEntity) -> None: ...

    def list_all(self) -> list[RankEntity]: ...

    def get_rank_by_pk(self, pk: int) -> RankEntity: ...

    def get_rank_by_name(self, name: str) -> RankEntity: ...

    def get_next_rank(self, current_points: int) -> RankEntity: ...
