# Generated by Django 5.1.7 on 2025-03-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_parent_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
