# Generated by Django 5.1.7 on 2025-03-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_thread_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='posts.tags'),
        ),
    ]
