# Generated by Django 5.1.7 on 2025-03-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_thread_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
