# Generated by Django 5.1.7 on 2025-03-17 19:32

import django.core.validators
import utils.image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='threads_cover', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), utils.image.validate_image_size, utils.image.validate_image_dimensions]),
        ),
    ]
