# Generated by Django 5.1.7 on 2025-04-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_thread_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='likes',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
