# Generated by Django 5.1.7 on 2025-04-17 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_thread_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='parent_post',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='likes',
        ),
        migrations.AddField(
            model_name='thread',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_threads', to=settings.AUTH_USER_MODEL),
        ),
    ]
